// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateAccount struct {
	Email     string `json:"email"`
	CountryID int    `json:"countryId"`
}

type FinalizeAccount struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
}

type InsertReport struct {
	ReporterID        int    `json:"reporterId"`
	ReportedID        int    `json:"reportedId"`
	ReportDescription string `json:"reportDescription"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PromoInput struct {
	PromoDiscount int `json:"promoDiscount"`
	PromoDuration int `json:"promoDuration"`
	GameID        int `json:"gameId"`
}

type Email struct {
	Email string `json:"Email"`
}

type GameInput struct {
	ID                int    `json:"ID"`
	Name              string `json:"Name"`
	Description       string `json:"Description"`
	Price             int    `json:"Price"`
	Rating            int    `json:"Rating"`
	ImageBanner       string `json:"imageBanner"`
	Image             string `json:"Image"`
	Tag               string `json:"tag"`
	SystemRequirement string `json:"systemRequirement"`
}
