// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateAccount struct {
	Email     string `json:"email"`
	CountryID int    `json:"countryId"`
}

type FinalizeAccount struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Email struct {
	Email string `json:"Email"`
}
